import { greaterThan, required, validateArray, Validator } from '@shaval/validation'
import { expectAssignable, expectError } from 'tsd'

expectAssignable<Validator<string[]>>(validateArray())
expectAssignable<Validator<number[]>>(validateArray())
expectAssignable<Validator<boolean[]>>(validateArray())
expectAssignable<Validator<null[]>>(validateArray())
expectAssignable<Validator<undefined[]>>(validateArray())
expectAssignable<Validator<(string | undefined)[]>>(validateArray())
expectAssignable<Validator<(string | null)[]>>(validateArray())
expectAssignable<Validator<(string | undefined | null)[]>>(validateArray())
expectAssignable<Validator<string[][]>>(validateArray())
expectAssignable<Validator<{ s: string }[]>>(validateArray())

expectAssignable<Validator<string[]>>(validateArray(required))
expectAssignable<Validator<number[]>>(validateArray(required))
expectAssignable<Validator<boolean[]>>(validateArray(required))
expectAssignable<Validator<null[]>>(validateArray(required))
expectAssignable<Validator<undefined[]>>(validateArray(required))
expectAssignable<Validator<(string | undefined)[]>>(validateArray(required))
expectAssignable<Validator<(string | null)[]>>(validateArray(required))
expectAssignable<Validator<(string | undefined | null)[]>>(validateArray(required))
expectAssignable<Validator<string[][]>>(validateArray(required))
expectAssignable<Validator<{ s: string }[]>>(validateArray(required))

expectError<Validator<string[]>>(validateArray(greaterThan(0)))
expectAssignable<Validator<number[]>>(validateArray(greaterThan(0)))
expectError<Validator<boolean[]>>(validateArray(greaterThan(0)))
expectAssignable<Validator<null[]>>(validateArray(greaterThan(0)))
expectAssignable<Validator<undefined[]>>(validateArray(greaterThan(0)))
expectAssignable<Validator<(number | undefined)[]>>(validateArray(greaterThan(0)))
expectAssignable<Validator<(number | null)[]>>(validateArray(greaterThan(0)))
expectAssignable<Validator<(number | undefined | null)[]>>(validateArray(greaterThan(0)))
expectError<Validator<string[][]>>(validateArray(greaterThan(0)))
expectError<Validator<{ s: string }[]>>(validateArray(greaterThan(0)))

expectError<Validator<string[]>>(validateArray(required, greaterThan(0)))
expectAssignable<Validator<number[]>>(validateArray(required, greaterThan(0)))
expectError<Validator<boolean[]>>(validateArray(required, greaterThan(0)))
expectAssignable<Validator<null[]>>(validateArray(required, greaterThan(0)))
expectAssignable<Validator<undefined[]>>(validateArray(required, greaterThan(0)))
expectAssignable<Validator<(number | undefined)[]>>(validateArray(required, greaterThan(0)))
expectAssignable<Validator<(number | null)[]>>(validateArray(required, greaterThan(0)))
expectAssignable<Validator<(number | undefined | null)[]>>(validateArray(required, greaterThan(0)))
expectError<Validator<string[][]>>(validateArray(required, greaterThan(0)))
expectError<Validator<{ s: string }[]>>(validateArray(required, greaterThan(0)))
